"use client";

import { useState, type ReactNode } from "react";
import { useLanguage } from "../site-language";

export function BrandTheme({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [language] = useLanguage();
  const french = language === "fr";
  return <main className="detailPage brandPage" data-brand-theme={theme}>
    {children}
    <aside className="brandThemeToggle" role="group" aria-label={french ? "Thème de la page marque et documentaire" : "Brand and Documentary page theme"}>
      <button type="button" aria-pressed={theme === "light"} onClick={() => setTheme("light")}>{french ? "CLAIR" : "LIGHT"}</button>
      <button type="button" aria-pressed={theme === "dark"} onClick={() => setTheme("dark")}>{french ? "SOMBRE" : "DARK"}</button>
    </aside>
    <style>{`.brandThemeToggle{position:fixed;right:clamp(18px,3vw,42px);bottom:clamp(18px,3vw,34px);z-index:12;display:flex;padding:3px;border:1px solid rgba(213,170,85,.52);background:#080808}.brandThemeToggle button{border:0;padding:7px 9px;background:transparent;color:rgba(255,255,255,.58);cursor:pointer;font:800 .52rem/1 inherit;letter-spacing:.12em}.brandThemeToggle button[aria-pressed="true"]{background:var(--gold);color:#080808}
.brandPage[data-brand-theme="light"]{background:#f1ede4!important;color:#191611!important}.brandPage[data-brand-theme="light"] .detailHero.toneBrand{background:radial-gradient(circle at 80% 30%,rgba(213,170,85,.13),transparent 32%),#f1ede4!important}.brandPage[data-brand-theme="light"] .detailHero h1,.brandPage[data-brand-theme="light"] .weddingSectionHead h2,.brandPage[data-brand-theme="light"] .commercialProjectInfo h3,.brandPage[data-brand-theme="light"] .documentaryInfo strong,.brandPage[data-brand-theme="light"] .brandClosing h2{color:#191611!important}.brandPage[data-brand-theme="light"] .detailHero>div>p:not(.kicker),.brandPage[data-brand-theme="light"] .weddingSectionHead>p,.brandPage[data-brand-theme="light"] .commercialProjectInfo p,.brandPage[data-brand-theme="light"] .documentaryInfo p,.brandPage[data-brand-theme="light"] .brandClosing p{color:rgba(25,22,17,.66)!important}.brandPage[data-brand-theme="light"] .brandCollection,.brandPage[data-brand-theme="light"] .documentaryCollection,.brandPage[data-brand-theme="light"] .brandClosing{background:transparent!important;border-color:rgba(42,35,26,.15)!important}.brandPage[data-brand-theme="light"] .brandClosing::before,.brandPage[data-brand-theme="light"] .documentaryCard3::before{background:linear-gradient(135deg,rgba(213,170,85,.10),transparent 55%)!important}
.brandPage[data-brand-theme="light"] .brand-booking-label{color:rgba(25,22,17,.56)}.brandPage[data-brand-theme="light"] .brand-booking-choice{border-color:rgba(42,35,26,.24);background:rgba(255,253,247,.5);color:#191611}.brandPage[data-brand-theme="light"] .brand-booking-choice:hover{border-color:var(--gold);background:rgba(213,170,85,.12)}.brandPage[data-brand-theme="light"] .brandFilm,.brandPage[data-brand-theme="light"] .documentaryCard{border-color:rgba(42,35,26,.16)}.brandPage[data-brand-theme="light"] .brandCollaborationRail{border-color:rgba(42,35,26,.14);background:rgba(255,253,247,.36)}
.brandPage[data-brand-theme="light"] .brandCommercialCapabilities{color:#191611;background:rgba(255,253,247,.34)}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities h2,.brandPage[data-brand-theme="light"] .brandCommercialCapabilities h3{color:#191611}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities p{color:rgba(25,22,17,.62)}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities article{border-color:rgba(42,35,26,.15);background:rgba(255,253,247,.5)}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities article:hover{background:#f8f4ea;border-color:rgba(213,170,85,.52);box-shadow:0 16px 34px rgba(45,35,22,.12)}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities article:hover h3{color:#191611}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities article:hover p{color:rgba(25,22,17,.72)}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities [class*="hoverDetails"]{border-color:rgba(213,170,85,.45);border-top-color:rgba(42,35,26,.12);background:#f8f4ea;color:rgba(25,22,17,.72)}.brandPage[data-brand-theme="light"] .brandCommercialCapabilities [class*="deliveryItems"] span{border-color:rgba(42,35,26,.17);color:rgba(25,22,17,.62)}`}</style>
  </main>;
}
