import { KSPPlayerLink } from "../ksp-player";
import { Localized } from "../site-language";
import ArchiveDisclosures from "./archive-disclosures";
import styles from "./documentary-case-study.module.css";
type Credit=[string,string,string[]];const bts=Array.from({length:27},(_,i)=>`/documentaries/les-12-rounds/les-12-rounds-bts-${String(i+1).padStart(2,"0")}.jpg`).filter((_,i)=>i!==12);const btsTeaser:string[]=["/documentaries/les-12-rounds/les-12-rounds-teaser-01.jpg","/documentaries/les-12-rounds/les-12-rounds-teaser-02.jpg","/documentaries/les-12-rounds/les-12-rounds-teaser-03.jpg","/documentaries/les-12-rounds/les-12-rounds-teaser-04.jpg"];const people=["Ariane Moffatt","Bruno Pelletier","Cathy Gauthier","Dan Bigras","Denis Coderre","Ève Landry","Dramatik","Simon Boulerice","Chantal Rouleau","Marc Hervieux","Manuel Tadros","Josélito Michaud","Robert Frosi","Anie Samson","Lynda Thalie","Patrice Godin","Eddy King","David Heurtel","Sébastien Delorme","Stéphanie Glorieux","Soraya Martinez","Rémi Bourget","Michael Penner","Alexandre Landry","Pénélope McQuade","Jean Cantin","Dominic St-Laurent","Hassoun Camara"];const imdb="https://www.imdb.com/name/nm10634739/";
const les:Credit[]=[["DIRECTOR","RÉALISATION",["Jean-Marie Benoit"]],["ASSISTANT DIRECTOR","ASSISTANTE À LA RÉALISATION",["Cynthia Barbin"]],["CAMERA","CAMÉRA",["Kevin Shayne","Jean-Marie Benoit","Colby Ollyhoo"]],["EDITING","MONTAGE",["Kevin Shayne"]],["MAIN SUBJECT","SUJET PRINCIPAL",["Ali Nestor"]]];const production:Credit[]=[["DIRECTION","RÉALISATION",["Benny de QCULTR","Koudjo Oni"]],["CAMERA","CAMÉRA",["Kevin Shayne"]],["CAMERA ASSISTANCE","ASSISTANCE À LA CAMÉRA",["Jayne Petigny"]],["EDITING","MONTAGE",["Kevin Shayne"]]];
const amplifyProject={title:"AMPLIFY SEASON ONE · ADVANCE TORONTO",meta:["SERIES · SEASON 1 · 2022","SÉRIE · SAISON 1 · 2022"],copy:["AMPLIFY Season 1 is an ADVANCE interview series built around the journeys, lessons and professional realities of Black Canadian entertainment professionals, using candid conversations as a form of accessible industry mentorship.","La saison 1 d’AMPLIFY est une série d’entrevues d’ADVANCE consacrée aux parcours, aux apprentissages et aux réalités professionnelles de personnes noires œuvrant dans l’industrie canadienne du divertissement, à travers des conversations franches pensées comme une forme de mentorat accessible."],credits:[["DIRECTION","RÉALISATION",["Benny de QCULTR","Koudjo Oni"]],["CAMERA","CAMÉRA",["Kevin Shayne"]],["CAMERA ASSISTANCE","ASSISTANCE À LA CAMÉRA",["Jayne Petigny"]],["EDITING","MONTAGE",["Kevin Shayne"]]] as Credit[]};const amplifyEpisodes=[
["Ursdlc6oGug","AMPLIFY Season 1 Official Trailer"],
["FWDH4X4oYmk","Just Getting Started | Episode 1 - The AMPLIFY Podcast by ADVANCE | Season 1"],
["wB40yuyHmMk","Hustle, Hustle, Hustle | Episode 2 - The AMPLIFY Podcast by ADVANCE | Season 1"],
["EqxJ4yi1oZs","Walk Good | Episode 3 - The AMPLIFY Podcast by ADVANCE | Season 1"],
["__lXt39bXBI","Can You Have It All | Episode 4 - The AMPLIFY Podcast by ADVANCE | Season 1"],
["4j5guO4RfZs","Morale Compass | Episode 5 - The AMPLIFY Podcast Season 1"],
["lG-8HfKfTvA","All Will Be Well In The End | Episode 6 - The AMPLIFY Podcast Season 1"],
["YwVNkUrP0RY","Behind The Scenes of AMPLIFY | Episode 7 - The AMPLIFY Podcast Season 1"]
] as const;

const advance=[
["PEkShBBPLVo","Rêver, Croire et Foncer | Épisode 8 - Le balado AMPLIFY | Saison 1","09"],
["6FSUnr_jmp0","La route vers la gloire | Épisode 9 - Le balado AMPLIFY | Saison 1","10"],
["QcDHkjJcruA","REJOIGNEZ ADVANCE QUÉBEC !",""],
["06Y1shvRsRk","CORNEILLE PRÉSENTE ADVANCE QUÉBEC",""],
["SSXpVDwlsJM","QUÉBEC ET LE R&B : UNE NOUVELLE CATÉGORIE",""],

] as const;
function Credits({items}:{items:Credit[]}){return <div className={styles.credits}>{items.map(([en,fr,n])=><div key={en}><small><Localized en={en} fr={fr}/></small>{n.map(x=>x==="Kevin Shayne"?<a key={x} href={imdb} target="_blank" rel="noopener noreferrer" aria-label="Kevin Shayne on IMDb">{x}</a>:<span key={x}>{x}</span>)}</div>)}</div>}function Poster({id,title,large=false,previewSrc}:{id:string;title:string;large?:boolean;previewSrc?:string}){return <KSPPlayerLink className={large?styles.film:styles.poster} video={{sourceType:"youtube",source:id,title}}>{previewSrc?<video src={previewSrc} autoPlay muted loop playsInline preload="metadata" aria-hidden="true" style={{width:"100%",display:"block",objectFit:"cover"}}/>:<img src={`https://i.ytimg.com/vi/${id}/hqdefault.jpg`} alt="" loading={large?"eager":"lazy"}/>}<strong className={styles.hoverTitle}>{title}</strong><span><Localized en="WATCH FILM" fr="VOIR LE FILM"/> ↗</span></KSPPlayerLink>}
function AmplifySeason(){return <article className={`${styles.caseStudy} ${styles.standard}`}><div className={styles.heading}><p><Localized en="DOCUMENTARY ARCHIVE" fr="ARCHIVES DOCUMENTAIRES"/></p><h3>{amplifyProject.title}</h3><span><Localized en={amplifyProject.meta[0]} fr={amplifyProject.meta[1]}/></span></div><div className={styles.story}><p><Localized en={amplifyProject.copy[0]} fr={amplifyProject.copy[1]}/></p></div><div className={styles.episodeHead}><Localized en={`SEASON 1 · ${amplifyEpisodes.length} VIDEOS`} fr={`SAISON 1 · ${amplifyEpisodes.length} VIDÉOS`}/></div><div className={styles.episodeGallery}>{amplifyEpisodes.map(([id,title],i)=><div key={id}><Poster id={id} title={title}/><small>{String(i+1).padStart(2,"0")} · {title}</small></div>)}</div><Credits items={amplifyProject.credits}/></article>}function Advance(){return <article className={`${styles.caseStudy} ${styles.standard}`}><div className={styles.heading}><p><Localized en="DOCUMENTARY ARCHIVE" fr="ARCHIVES DOCUMENTAIRES"/></p><h3>ADVANCE QUÉBEC</h3><span><Localized en="FIVE-FILM COLLECTION · QUÉBEC · 2022–2023" fr="COLLECTION DE CINQ FILMS · QUÉBEC · 2022–2023"/></span></div><div className={styles.story}><p><Localized en="A five-film body of work for ADVANCE Québec, documenting a community supporting Black music professionals, elevating representation and advocating for recognition of Black music and R&B in Québec." fr="Un corpus de cinq films pour ADVANCE Québec, qui documente une communauté soutenant les professionnel·les noir·es de la musique, valorisant la représentation et défendant la reconnaissance des musiques noires et du R&B au Québec."/></p></div><div className={styles.miniGallery}>{advance.map(([id,title,index])=><div key={id}><Poster id={id} title={title}/><small>{index ? `${index} · ` : ""}{title}</small></div>)}</div><Credits items={production}/></article>}
export default function DocumentaryCaseStudies(){return <section className={`${styles.section} documentaryArchiveCases`}><div className={styles.transition}><Localized en="ARCHIVE" fr="ARCHIVES"/></div><article className={styles.caseStudy}><div className={styles.heading}><p><Localized en="DOCUMENTARY ARCHIVE" fr="ARCHIVES DOCUMENTAIRES"/></p><h3>LES 12 ROUNDS DE L’ESPOIR</h3><span>ALI NESTOR · MONTRÉAL, QUÉBEC · 2019</span></div><div className={styles.grid}><div className={styles.mediaColumn}><Poster large id="0COeoDUxR8A" title="LES 12 ROUNDS DE L’ESPOIR" previewSrc="/brand-documentary/les-12-rounds-thumbnail.mp4"/><div className={styles.eventNote}><small><Localized en="THE EVENT" fr="L’ÉVÉNEMENT"/></small><p><Localized en="On May 30, 2019, the second edition of Les 12 Rounds de l’Espoir brought artists and public figures into the ring in Montréal in support of Ali et les Princes/esses de la Rue, the organization founded by Ali Nestor that uses boxing and martial arts to support young people, encourage school engagement and build confidence." fr="Le 30 mai 2019, la deuxième édition des 12 Rounds de l’Espoir a réuni à Montréal artistes et personnalités publiques sur le ring au profit d’Ali et les Princes/esses de la Rue, l’organisme fondé par Ali Nestor qui utilise la boxe et les arts martiaux pour soutenir les jeunes, favoriser leur persévérance scolaire et renforcer leur confiance."/></p></div></div><div className={styles.story}><small><Localized en="THE FILM" fr="LE FILM"/></small><p><Localized en="Set around the 2019 edition of Les 12 Rounds de l’Espoir, the film follows Ali Nestor as he prepares artists, athletes and public figures to step into the ring for a Montreal fundraising event." fr="Au cœur de l’édition 2019 des 12 Rounds de l’Espoir, le film suit Ali Nestor alors qu’il prépare artistes, athlètes et personnalités publiques à monter sur le ring pour un événement-bénéfice montréalais."/></p><p className={styles.context}><Localized en="Moving between training, mentorship and community work, the documentary reveals the person behind the event and the mission driving his work with young people." fr="Entre entraînement, transmission et engagement communautaire, le documentaire révèle l’homme derrière l’événement et la mission qui anime son travail auprès des jeunes."/></p><Credits items={les}/></div></div><ArchiveDisclosures people={people} bts={bts} teaser={btsTeaser}/></article><AmplifySeason/><Advance/></section>}
