import { Localized, SiteFooter, SiteHeader } from "../site-language";

const commercial = [{ title: "Barbancourt", type: "Commercial film", youtubeId: "hNRG8NT3sRs" }, { title: "Fragrance", type: "Product campaign", youtubeId: "FYL9RmYlZ6U" }];
const documentaries = [
  { title: "Corneille présente ADVANCE Québec", src: "https://github.com/kspvision/kspvision-site/releases/download/hero-reel-2026-08-15/Corneille.presente.ADVANCE.Quebec.mp4" },
  { title: "Finance Montréal", poster: true },
  { title: "Kevin Shayne Story", src: "https://raw.githubusercontent.com/kspvision/kspvision-site/main/public/documentary/kevin-shayne-story-preview.mp4", preview: true },
];

export default function Page() { return <main className="detailPage brandPage"><SiteHeader active="brand" />
  <section className="detailHero toneBrand"><div><p className="kicker">BRAND & DOCUMENTARY</p><h1><Localized en="Stories with purpose." fr="Des histoires qui comptent." /></h1><p><Localized en="Commercial films and documentary work with clarity, character and a human point of view." fr="Des films commerciaux et documentaires avec clarté, caractère et un regard humain." /></p><a className="button gold" href="/booking"><Localized en="Start a project" fr="Lancer un projet" /> <b>↗</b></a></div></section>
  <section className="brandCollection"><div className="weddingSectionHead"><div><p className="kicker"><Localized en="Selected work" fr="Travaux sélectionnés" /></p><h2><Localized en="Commercial stories" fr="Histoires de marque" /></h2></div></div><div className="brandGrid">{commercial.map((project) => <a className="brandFilm" href={`https://www.youtube.com/watch?v=${project.youtubeId}`} target="_blank" rel="noreferrer" key={project.title}><div className="publishedFilmStill"><img src={`https://img.youtube.com/vi/${project.youtubeId}/hqdefault.jpg`} alt="" /><span><Localized en="Watch film" fr="Voir le film" /> ↗</span></div><div><p>{project.type}</p><h3>{project.title}</h3></div></a>)}</div></section>
  <section className="brandCollection documentaryCollection"><div className="weddingSectionHead"><div><p className="kicker">DOCUMENTARY</p><h2><Localized en="Real stories" fr="Histoires réelles" /></h2></div><p><Localized en="Portraits and conversations made with attention and care." fr="Des portraits et conversations réalisés avec attention et sensibilité." /></p></div><div className="brandGrid">{documentaries.map((project) => <article className="brandFilm" key={project.title}>{project.poster ? <div className="documentaryPoster financePoster" aria-label="Finance Montréal documentary preview"><span>FINANCE<br/>MONTRÉAL</span><small>DOCUMENTARY PREVIEW</small></div> : <video autoPlay muted loop playsInline preload="metadata"><source src={project.src} type="video/mp4" /></video>}<div><p>{project.preview ? "DOCUMENTARY PROJECT · PREVIEW" : "DOCUMENTARY"}</p><h3>{project.title}</h3></div></article>)}</div></section><SiteFooter /></main>; }
